[package]
name = "goop"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
colored = "3.0.0"
inkwell = { version = "0.6.0", features = ["llvm18-1"] }
